### ISSUE TITLE
support multiple relations per service

### ISSUE THREAD

**Issue by jamesbeedy** [juju-solutions/interface-http#5]
Currently it seems this interface only provides support for one host/port config per service.

It would be nice to be able to do something like

``` yaml
provides:
  http:
    interface: http
  https:
    interface: http
```

``` python
@when('http.available')
def configure_http(http):
    http.configure(80)

@when('https.available')
def configure_https(https):
    https.configure(443)
```
